version: '3.8'

services:
  jupyter:
    image: jupyter/base-notebook:latest  
    container_name: jupyter_notebook
    ports:
      - "8888:8888"   # Puerto local:contenedor
    volumes:
      - ./notebooks:/home/jovyan/work   # Carpeta local → carpeta en el contenedor
    environment:
      - JUPYTER_TOKEN=1234  
    restart: unless-stopped
